version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: ctl-api-example-client
    network_mode: host
  go-server:
    build:
      context: .
      dockerfile: Dockerfile.go-server
    image: ctl-api-example-go-server
    network_mode: host
    volumes:
      - /tmp/toC:/tmp/toC
      - /tmp/fromC:/tmp/fromC
