version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: ctl-api-example-client
    ports:
      - "8086:8086"
  go-server:
    build:
      context: .
      dockerfile: Dockerfile.go-server
    image: ctl-api-example-go-server
    ports:
      - "8085:8085"
    volumes:
      - shared-pipes:/tmp
  c-server:
    build:
      context: .
      dockerfile: Dockerfile.c-server
    image: ctl-api-example-c-server
    volumes:
      - shared-pipes:/tmp

volumes:
  shared-pipes:
