/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "demo_protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(demo_protocol_HostPayload, demo_protocol_HostPayload, 4)


PB_BIND(demo_protocol_ClientPayload, demo_protocol_ClientPayload, 2)


PB_BIND(demo_protocol_CommandResponse, demo_protocol_CommandResponse, AUTO)


PB_BIND(demo_protocol_Command, demo_protocol_Command, AUTO)


PB_BIND(demo_protocol_StatusOk, demo_protocol_StatusOk, AUTO)


PB_BIND(demo_protocol_StatusError, demo_protocol_StatusError, AUTO)


PB_BIND(demo_protocol_SetZoomLevel, demo_protocol_SetZoomLevel, AUTO)


PB_BIND(demo_protocol_SetColorScheme, demo_protocol_SetColorScheme, AUTO)


PB_BIND(demo_protocol_GetHostDevStatus, demo_protocol_GetHostDevStatus, AUTO)


PB_BIND(demo_protocol_GetHostProfile, demo_protocol_GetHostProfile, AUTO)


PB_BIND(demo_protocol_SetAirTemp, demo_protocol_SetAirTemp, AUTO)


PB_BIND(demo_protocol_SetPowderTemp, demo_protocol_SetPowderTemp, AUTO)


PB_BIND(demo_protocol_SetAirHumidity, demo_protocol_SetAirHumidity, AUTO)


PB_BIND(demo_protocol_SetAirPressure, demo_protocol_SetAirPressure, AUTO)


PB_BIND(demo_protocol_SetWind, demo_protocol_SetWind, AUTO)


PB_BIND(demo_protocol_SetDistance, demo_protocol_SetDistance, AUTO)


PB_BIND(demo_protocol_SetAgcMode, demo_protocol_SetAgcMode, AUTO)


PB_BIND(demo_protocol_SetCompassOffset, demo_protocol_SetCompassOffset, AUTO)


PB_BIND(demo_protocol_SetHoldoff, demo_protocol_SetHoldoff, AUTO)


PB_BIND(demo_protocol_ButtonPress, demo_protocol_ButtonPress, AUTO)


PB_BIND(demo_protocol_TriggerCmd, demo_protocol_TriggerCmd, AUTO)


PB_BIND(demo_protocol_SetZeroing, demo_protocol_SetZeroing, AUTO)


PB_BIND(demo_protocol_HostDevStatus, demo_protocol_HostDevStatus, AUTO)


PB_BIND(demo_protocol_ClientDevStatus, demo_protocol_ClientDevStatus, AUTO)


PB_BIND(demo_protocol_CoefRow, demo_protocol_CoefRow, AUTO)


PB_BIND(demo_protocol_SwPos, demo_protocol_SwPos, AUTO)


PB_BIND(demo_protocol_HostProfile, demo_protocol_HostProfile, 2)


PB_BIND(demo_protocol_ClientProfile, demo_protocol_ClientProfile, AUTO)













